### ISSUE TITLE
Disappeared?

### ISSUE THREAD

**Issue by wout** [tomatoers/tomato#53] opened 2018-11-07 10:57 UTC
I'd love to use this app but I can't find it in Juno's AppCentre. Did you pull it?

**Comment by ryonakano** [comment] 2018-11-07 10:59
Unfortunately it's not released for Juno yet, please see #50 (and this is duplicated)

**Comment by megatux** [comment] 2018-11-07 12:29
I'm a member of "tomatoers" that cassidyjames created for this. Still can't close this issue :man_shrugging:. @luizaugustomm could you add the repo to that org? (https://github.com/tomatoers)

**Comment by luizaugustomm** [comment] 2018-11-07 13:19
Sorry for the delay, @megatux. I had transferred the repository to Cassidy instead. But the Tomatoers own Tomato now.

By the way, I'm very happy you are putting some effort to keep Tomato alive. :)

**Comment by cassidyjames** [comment] 2018-11-21 21:35
Considering this as a dupe of #50

**Closed by cassidyjames** 2018-11-21 21:35 UTC
