### ISSUE TITLE
Impossible to change the workspace where pomodoro is at.

### ISSUE THREAD

**Issue by Marcos-Costa** [tomatoers/tomato#42] opened 2017-10-31 11:31 UTC
When you're using pomodoro and try to move it to another workspace (⌘+S), the program does not show up as one of the running programs.

**Comment by cassidyjames** [comment] 2018-11-21 23:55
Thanks for reporting! I know this was reported first, but I'm going to file it as a duplicate of #46 since there's more activity and info over there.

**Closed by cassidyjames** 2018-11-21 23:55 UTC
